### ISSUE TITLE
La lista no puede tener diferentes cantidades de claves y de valores

### ISSUE THREAD

**Issue by evolentini** [jmorellid/testing_clase4#2]
No se deben sestear detalles de implementación, la idea de utilizar dos arreglos independientes no debe influir en las pruebas. Por definición la lista solo almacena parejas, y por lo tanto no puede tener una cantidad diferentes de claves que de valores.

**Comment by jmorellid** [comment]
Modificado para testear cantidad de claves y elementos en un mismo test.
