### ISSUE TITLE
No se aplicó correctamente la metodología propuesta.

### ISSUE THREAD

**Issue by evolentini** [jmorellid/testing_clase4#4]
En el método delete se genera una expresión cuando el valor a borrar no existe, pero ninguna prueba revisa ese código. Esto no se escribió para resolver una prueba unitaria que falla.

https://github.com/jmorellid/testing_clase4/blob/91827d186979d2ba2d1ff15ce26e4659fe192f63/src/lista.py#L41-L48

**Comment by jmorellid** [comment]
Agregado el escenario de prueba del eliminado de una clave inexistente
